name: Build and Test
on: [push, workflow_dispatch]
jobs:
  WebApp-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore Eventures.WebApp.SeleniumTests
      - run: dotnet build Eventures.WebApp.SeleniumTests --no-restore
      - run: dotnet test Eventures.WebApp.SeleniumTests --no-build --verbosity normal
      - run: dotnet restore Eventures.WebApp.SeleniumPOMTests
      - run: dotnet build Eventures.WebApp.SeleniumPOMTests --no-restore
      - run: dotnet test Eventures.WebApp.SeleniumPOMTests --no-build --verbosity normal
